spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8888
      name: auth-service
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/