spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
      name: api-gateway
      label: main
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/