server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthFilter
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/videos/**
          filters:
            - AuthFilter
        - id: danmu-service
          uri: lb://danmu-service
          predicates:
            - Path=/api/danmus/**
          filters:
            - AuthFilter
        - id: ad-service
          uri: lb://ad-service
          predicates:
            - Path=/api/ads/**
          filters:
            - AuthFilter
        - id: recommend-service
          uri: lb://recommend-service
          predicates:
            - Path=/api/recommend/**
          filters:
            - AuthFilter
        - id: like-collect-service
          uri: lb://like-collect-service
          predicates:
            - Path=/api/like-collect/**
          filters:
            - AuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: debug