server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dilidili_video?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost