spring:
  application:
    name: video-service
  cloud:
    config:
      uri: http://localhost:8888
      name: video-service
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
video:
  storage:
    path: /path/to/storage/ # 替换为实际存储路径