spring:
  application:
    name: user-service
  profiles:
    active: dev
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: debug
    qinghuan.user: debug