server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true