server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dilidili_video?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
video:
  storage:
    path: /path/to/storage/