server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qinghuan11/dilidili_springcloud
          search-paths: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: debug