server:
  port: 8888
spring:
  application:
    name: config-server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Users/yh/IdeaProjects/dilidili_springcloud/config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
logging:
  level:
    root: debug
    org.springframework.cloud: debug